MC:
  vars:
    mass_wet:
      standard_name: mass_wet
      search_regex: '(mass_wet)|(wet_mass)|(wmt)'  # case in-sensitive regex
    mass_dry:
      standard_name: mass_dry
      search_regex: '(mass_dry)|(dry_mass)|(dmt)'
    moisture:
      standard_name: H2O
      search_regex: '(h2o)|(moisture)|(moist)'
    chemistry:
      ignore: ['Y']  # ignore anything in this list when detecting chemistry components
  units:
    mass: mass_units
    composition_rel: '%'
  constraints:
    mass: [0.0, .inf]
    composition: [0.0, 100.0]
  intervals:
    closed: left
    suffixes:
      - [from, to]
      - [retained, passing]
      - [sink, float]
  comparisons:
    recovery: 'rec'
    difference: 'diff'
    divide: 'ur'

